### ISSUE TITLE
Insufficient capacity on K3s (apparently incorrectly)

### ISSUE THREAD

**Issue by funkypenguin** [cybozu-go/topolvm#120]
**Describe the bug**

On a fresh deployment of k3s, I try to deploy a 1Gi PVC, and the associated pod can't start because:

```
0/1 nodes are available: 1 Insufficient topolvm.cybozu.com/capacity.
```

The pod expects:

```
    Limits:
      topolvm.cybozu.com/capacity:  1073741824
    Requests:
      topolvm.cybozu.com/capacity:  1073741824
```

And the node has:

```
topolvm.cybozu.com/capacity: 42945478656
```

**Environments**
- Version: K3s 1.17.3
- OS: Ubuntu 1804

**To Reproduce**
1. Deploy TopoLVM per instructions
2. Create a 1Gi PVC
3. Create a pod to consume the PVC

**Expected behavior**
The PVC is correctly allocated from the available space on the node
