### ISSUE TITLE
Multiple StorageClasses

### ISSUE THREAD

**Issue by temujin9** [cybozu-go/topolvm#125]
## What

Some use cases of TopoLVM are on big data systems with SSDs. It would be nice to support them as a separate StorageClass, so that disk performance can be selected for.

## How

Add a parameter to StorageClass that sets the target volume group. That might also free from the need to specify it via the systemd startup line, although it might be prudent to have an allow-list / block-list to prevent messing with system volume groups.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by deveshk0** [comment]
Much needed enhancement.

**Comment by deveshk0** [comment]
@ymmt2005 Thanks for taking this up

**Comment by ymmt2005** [comment]
@deveshk0 You are welcome!
We are considering this seriously now as there seems a handful of potential users.

**Comment by leonenkoa** [comment]
I think if we consider to support multiple volume groups with separate StorageClass, makes sense to create volume group for specific StorageClass, what do you think ?

**Comment by ymmt2005** [comment]
Do you mean one volume group for one StorageClass?
I don't think so because StorageClass has other options such as filesystem type.

**Comment by leonenkoa** [comment]
So we should bind somehow volume groups,filesystems and StorageClasses and I don't have any other idea except to provision all this parts with TopoLVM i.e. with some other service.

**Comment by deveshk0** [comment]
We have come up with something like this - 

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-sdd
provisioner: topolvm.cybozu.com
parameters:
  "csi.storage.k8s.io/fstype": "xfs"
  "topolvm.cybozu.com/vol-group": "ssd-group"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-hdd
provisioner: topolvm.cybozu.com
parameters:
  "csi.storage.k8s.io/fstype": "xfs"
  "topolvm.cybozu.com/vol-group": "hdd-group"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

This parameters are available  while creating the volume.
